package ir

type linkSym struct {
	fill int
	pkg  string // package path, empty string for the same package
	sym  string // symbol name
}

type inst struct {
	inst uint32
	sym  *linkSym // generated by FuncSym or VarSym on code gen
}
